apiVersion: v1
kind: Pod
metadata: 
  name: myngpod
spec: 
  imagePullSecrets:
    - name: mydhubsecr
  containers:
    - image: ajbhise2609/mynginx:v1.0
      name: myngcont
      ports:
       - containerPort: 80

