apiVersion: v1
kind: ReplicationController
metadata:
   name: replicawala
spec:
  replicas: 7
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
         - image: nginx
           name: ngcontainer
           ports:
            - containerPort: 80
           livenessProbe:
                httpGet:
                    path: /index.html
                    port: 80
                periodSeconds: 10
                initialDelaySeconds: 10
