apiVersion: v1
kind: Pod 
metadata: 
  name: myngpod1
  labels:
     website: nginx
spec:
  containers:
    - image: nginx
      name: myngcont
      ports:
        - containerPort: 80
          hostPort: 80  
