apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvclaim
  labels: 
    app: pypvc

spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: dev

