apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrsetngpod
spec: 
  replicas: 3
  selector:
    matchLabels:   
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
       - image: nginx 
         name: ngcont
         ports: 
          - containerPort: 80
