apiVersion: v1
kind: Pod 
metadata: 
  name: myngpod
  labels:
     app: nginx

spec:
 
  containers:
    - image: nginx
      name: myngcont
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: htmlfolder
          mountPath: /usr/share/nginx/html  
  volumes:
    - name: htmlfolder
      nfs:
       server: "fs-042b9ee02c19f5f81.efs.ap-south-1.amazonaws.com"
       path: /test
 

